### ISSUE TITLE
ekt.h includes srtp_priv.h, which is not installed

### ISSUE THREAD

**Issue by Lastique** [cisco/libsrtp#219]
In libsrtp 2.0.0, the ekt.h header includes srtp_priv.h, which is not installed as part of the `install` target. Either srtp_priv.h and its dependencies should be installed as well, or ekt.h should not depend on it.

**Comment by pabuhler** [comment]
@paulej should the ekt.h header even be there? Is the implementation of ekt in master something that is complete and supported?

**Comment by paulej** [comment]
The ekt stuff that is currently in here is really non-functional.  We have a separate ekt_dev branch with a complete implementation of the avtcore draft.  That's going to be very challenging to merge with MKI changes going in.  Plus, the IETF PRIME WG is changing the EKT spec such that it might make sense to just re-write that code entirely.

Anyway, I think we can and probably should just remove all the EKT stuff right now, because it has no value.
