### ISSUE TITLE
libstrp email list

### ISSUE THREAD

**Issue by carlh54** [cisco/libsrtp#227]
Hi

Sorry if this is the wrong place to ask. 

I'm trying to get information through the libstrp users & developers email list but I get no responses nor do I see any email message digests come out.

Is that not the preferred method to ask questions?

thanks
/carl h.

**Comment by paulej** [comment]
I just created a mailing list that I'll maintain for the purpose of discussing issues, announcing new releases, etc. It's on http://lists.packetizer.com. It hasn't been announced, yet, so there aren't many people on the list, yet.

**Comment by carlh54** [comment]
Thanks Paul.

So in the mean time what should I use?

**Comment by paulej** [comment]
Posting here is as good as anything. There are a number of people watching the project.  Perhaps close this issue and open a new one with your question.

**Comment by carlh54** [comment]
Will do.
thx
/c

**Comment by carlh54** [comment]
Hi Paul,

Not getting much luck with my question.

Is there anyone that I can nudge to take a look?

thx
/carl

**Comment by paulej** [comment]
I think for getting up-to-date info, the answer is "read the source".  It might be good if somebody (perhaps one of the maintainers ... or you) could write a small tutorial on how to use the APIs.  The PDF that was deleted is actually still pretty good at providing an introduction, but somebody asked it to be deleted since much of it was dated.

As for why the documentation build stuff is not working, that sounds like something that needs to be explored.  Just leave it there.  Me or somebody will get to it eventually.

**Comment by carlh54** [comment]
ok thanks.
/carl
