### ISSUE TITLE
Warnings compiling on FreeBSD

### ISSUE THREAD

**Issue by paulej** [cisco/libsrtp#257]
The -pedantic compiler switch results in a number of compilation warnings.  We should investigate why and address the issues.

**Comment by pabuhler** [comment]
I have had some second thoughts about -pedantic, need to either be "pedantic" in our coding including comments or else start adding some exceptions for different compilers.

**Comment by paulej** [comment]
I did not explore all of the issues I saw, but some could be resolved by changing the code to conform to a specific C version.  Others I wasn't sure why the compiler was complaining, so I can't say what the issue was.

We might want to pass to the compiler the --std parameter.  I'm not sure what the compiler assumes by default.

**Comment by thisisG** [comment]
With gcc 6.3.1 it always fails compilation if any -std=cNN is specified. 

I thought it was left undefined in order to be "as portable as possible", especially if looking at how many different systems we try to accommodate for in `configure` as well as optional includes in for example `integers.h` to try to get c99(ish) types.

**Comment by pabuhler** [comment]
@paulej ,are there still a lot of warnings on FreeBSD ?

**Comment by paulej** [comment]
Not with gcc 7, at least.
