### ISSUE TITLE
Missing API  2.1.0-pre compared to 1.5.x

### ISSUE THREAD

**Issue by ulfolsson** [cisco/libsrtp#270]
Hi,
I'm using GStreamer for streaming media an I have encountered some problems when porting their SRTP 
plugin (https://cgit.freedesktop.org/gstreamer/gst-plugins-bad/tree/ext/srtp) to 2.1.0-pre. The problem is that some of the "private" API in 1.5.x was in fact public and I am thinking about the API that handles ROC and the initial sequence number. All of this is now private  in 2.1.0-pre. Attaching a patch that solves the problem [srtp.c.patch.zip](https://github.com/cisco/libsrtp/files/827260/srtp.c.patch.zip)

Regards,

Ulf

**Comment by paulej** [comment]
I assume the same issues exist with the 2.0 release that has been out for a while?

Why does GStreamer need access to that level of information?  The ROC isn't something the application generally needs to know or worry about.

Updating the sequence number seems a little odd, because that value is taken from the RTP packet when srtp_protect() is called.

The SRTP library really should look like a black box to applications.  If GStreamer is doing something that is more "low level", perhaps it might make more sense to just have that code within the GStreamer library to interface with internal SRTP functions.  The internal functions are subject to change, but they rarely do.

I would prefer to hear "why" and to get others' perspective on these changes.

**Comment by ulfolsson** [comment]
Basically there are two reasons
1. If you want to join an ongoing multicast stream you need the ROC
2.  The MIKEY RFC discuss more and less the same topic, look at section “6.1.1.  SRTP ID” and ROC_i

**Comment by pabuhler** [comment]
I can see that setting the ROC could be useful in some instances, there is some talk about the current ROC been shared out of bounds in order to join an existing stream, but why the seq number?

**Comment by ulfolsson** [comment]
Trying to get in touch with the author of that particular bit of code, stay tuned.

**Comment by sdroege** [comment]
The code in question is here btw, in case that makes sense to someone https://github.com/GStreamer/gst-plugins-bad/blob/master/ext/srtp/gstsrtpdec.c#L1160

It was added in https://github.com/GStreamer/gst-plugins-bad/commit/da30669589cfc8189f60aedfae98a217a9fae994 when support for setting ROC was added. AFAIU libsrtp wants to get the initial RTP seqnum together with the ROC there, but maybe this changed now and is not required anymore? I mean, libsrtp could as well extract the seqnum itself from the packet...

**Comment by sdroege** [comment]
Maybe let's just add @aconchillo directly to the conversation here :)

**Comment by aconchillo** [comment]
It's been a long time since I don't look at this.

We need the ROC in order to do multicast as @ulfolsson suggests, or in my case it was needed for unicast but sending the same encoded stream to multiple clients. I believe libsrtp should provide a way to get and set the ROC (and actually the replay database). We need to get access to the ROC so we can send it to the client with MIKEY. And as a client we need to be able to set the received ROC

About the sequence number: When the client receives a packet (from multicast or shared unicast) from an ongoing stream (i.e. ROC comes from MIKEY for example) it needs to set both, the ROC and the sequence number to initialize the replay database. This is what we do here:

https://github.com/GStreamer/gst-plugins-bad/blob/master/ext/srtp/gstsrtpdec.c#L1176

I'm not sure if that makes sense. I'm not an expert on this but this is what I gathered from reading the RFCs and the libsrtp code back in the day.

**Comment by pabuhler** [comment]
The problem I could see with only setting the ROC would be that when the next packet is processed the estimated index could be incorrect. To get around this either the current seq num needs to be set as it is in GStreamer today or else when setting the ROC a flag is set that the next packet will update the seq number without performing an estimation first.

I think I prefer the api:
```
srtp_err_status_t srtp_set_stream_roc(srtp_t session, uint32_t ssrc, uint32_t roc);
srtp_err_status_t srtp_get_stream_roc(srtp_t session, uint32_t ssrc, uint32_t *roc);
```
With caveat that setting the ROC will reset the replay database and the first rtp packet processed afterwards will update the seq num without performing an estimation calculation. I think it is better the libsrtp provide that kind of logic rather than requiring the application to manage it like the GStreamer code is doing today. @paulej  what do you think? this is the same logic needed/used for EKT.

There is also the problem of trying to set the ROC before the first packet when using template profiles, maybe we just say that is not supported.

**Comment by paulej** [comment]
Agree that an API is the safer option, as we can maintain it.  Any direct changes made to internal structures is likely to lead to exactly what we have here.  It's now "broken."

**Comment by ulfolsson** [comment]
Ok, thanks for the feedback. What happens next?

**Comment by pabuhler** [comment]
hmm, well either some one makes a new patch, or else I will see what I can do this week. It is a valid use case to set/get ROC so no real objections. Ideally some tests with regard to next seq number after setting ROC when seq number is either very low, very high, or very different to last seq ...

**Comment by ulfolsson** [comment]
I can give it a go the week after next (out of office next week)

<or else when setting the ROC a flag is set that the next packet 
<will update the seq number without performing an estimation firs

Do you mean something like

if (!stream->is_roc_set) {
  delta = srtp_rdbx_estimate_index(&stream->rtp_rdbx, &est, ntohs(hdr->seq));
} else {
  est = (srtp_xtd_seq_num_t) ntohs(hdr->seq);
  delta = (int)est;
  stream->is_roc_set = FALSE;
}

status = srtp_rdbx_check(&stream->rtp_rdbx, delta);

if (status) {
   if (status != srtp_err_status_replay_fail || !stream->allow_repeat_tx)
     return status;  /* we've been asked to reuse an index */
 } else
   srtp_rdbx_add_index(&stream->rtp_rdbx, delta);
.....

**Comment by pabuhler** [comment]
Something like that.
Not sure if the is_roc_set should be part of stream or rdbx, would need to see what makes most sense.
If you can push something early next week then we can review and test abit. I think making tests would be a good idea.

**Comment by pabuhler** [comment]
This should now be fixed in #289, closing now.
Would be good to know if GStream can now use v2.1 with out any issues!

**Comment by sdroege** [comment]
@ulfolsson can you confirm that this is all good now?

**Comment by sdroege** [comment]
There's a working patch for GStreamer here now: https://bugzilla.gnome.org/show_bug.cgi?id=776901
