### ISSUE TITLE
 configure.in:11: error: possibly undefined macro: AM_PROG_AR libsrtp 2.0.0 centos 6.9

### ISSUE THREAD

**Issue by mariarti** [cisco/libsrtp#296]
```
libsrtp-2.0.0]# autoconf
configure.in:11: error: possibly undefined macro: AM_PROG_AR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```
```
libbsrtp
v2.0.0
12ea269
```
```
# automake --version
automake (GNU automake) 1.11.1
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.

```

**Comment by mariarti** [comment]
commenting AM_PROG_AR allow to autoconf, but gives:
```
libsrtp-2.0.0]# make
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -c srtp/srtp.c -o srtp/srtp.o
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -c srtp/ekt.c -o srtp/ekt.o
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -c crypto/cipher/cipher.c -o crypto/cipher/cipher.o
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -c crypto/cipher/null_cipher.c -o crypto/cipher/null_cipher.o
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -c crypto/cipher/aes_icm.c -o crypto/cipher/aes_icm.o
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -c crypto/cipher/aes.c -o crypto/cipher/aes.o
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -c crypto/hash/null_auth.c -o crypto/hash/null_auth.o
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -c crypto/hash/auth.c -o crypto/hash/auth.o
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -c crypto/hash/hmac.c -o crypto/hash/hmac.o
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -c crypto/hash/sha1.c -o crypto/hash/sha1.o
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -c crypto/math/datatypes.c -o crypto/math/datatypes.o
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -c crypto/math/stat.c -o crypto/math/stat.o
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -c crypto/kernel/crypto_kernel.c -o crypto/kernel/crypto_kernel.o
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -c crypto/kernel/alloc.c -o crypto/kernel/alloc.o
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -c crypto/kernel/key.c -o crypto/kernel/key.o
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -c crypto/kernel/err.c -o crypto/kernel/err.o
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -c crypto/replay/rdb.c -o crypto/replay/rdb.o
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -c crypto/replay/rdbx.c -o crypto/replay/rdbx.o
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -c crypto/replay/ut_sim.c -o crypto/replay/ut_sim.o
make: AR@: Command not found
make: *** [libsrtp2.a] Error 127
[root@tradesv libsrtp-2.0.0]# make runtest
make: AR@: Command not found
make: *** [libsrtp2.a] Error 127

```

**Comment by itollefsen** [comment]
There's actually two issues here.

`AM_PROG_AR` was was introduced in Automake 1.11.2 and required starting with Automake 1.12. Well, "required" is too strong here. It's usually required when building libraries, but libsrtp doesn't use Automake for this so it's strictly speaking not required for that. However, `AM_PROG_AR` sets the "AR" variable used in the handwritten Makefile.in. And without that, you get the sort of build failures you're seeing.

Why you're getting the possibly undefined macro warning is somewhat puzzling since it's wrapped in a `m4_ifdef()` check. That needs a bit more thinking.

To sort out the build problems, we need to set "AR" even if `AM_PROG_AR` isn't defined. We could do something simple for now and assume that it will just be `ar`.

Could you try replace:
`m4_ifdef([AM_PROG_AR], [AM_PROG_AR])`
with:
`m4_ifdef([AM_PROG_AR], [AM_PROG_AR], [AC_SUBST([AR], [ar])])`

This really isn't a proper solution since it doesn't account for toolchain specific `ar` (if cross compiling for instance), but it's a start.

**Comment by itollefsen** [comment]
Another question is why do you need to regenerate the `configure` script? The pre-generated script is already checked in. I assume you needed to patch it for some reason?

The `AM_PROG_AR` macro only needs to be present for generating the script, not for running it (the code from the macro will be included in the `configure` script). It's therefore not out of the question to simply remove the `m4_ifdef()` check and require Automake 1.11.2 or newer for regenerating the script with autoconf, thereby making sure everyone running it gets the proper `ar` check without having to write a inferior fallback.

**Comment by mariarti** [comment]
Can't remember the root of the issue, but at that time I can't start `configure` without `autoconf` , but now it works without `autoconf`, and able to finish with `make` and `make install`.
thanks a lot!
(but now I have other/next issue)

**Comment by mjerris** [comment]
what i have done in the past for issues like this is include a file something like this in the source tree:

https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse/libs/sofia-sip/m4/sac-pkg-config.m4

and then in acincludes.m4 add a line like..

m4_include([libs/sofia-sip/m4/sac-pkg-config.m4])

with the right path.

It was way easier then answering all the questions of people who have pkg-config not installed, or surprisingly common, installed in weird locations so the m4 isnt found properly.

I can do up a patch for this if interested.

in regards to the AR issue, wrapping in the m4_ifdef should be enough

**Comment by itollefsen** [comment]
> in regards to the AR issue, wrapping in the m4_ifdef should be enough

For `autoreconf` to work, sure, but it will also lead to build failures because AR won't be set.

Since AR needs to be set, there's only two solutions: Require Automake 1.11.2 or newer if you want to regenerate the `configure` script with `autoreconf`, or write a "else" part to the m4_ifdef() and roll your own `ar` check. The latter is non-trivial given various platforms, use of cross compilers, etc.

I'll propose a patch that simply removes the m4_ifdef() check and uses AM_PROG_AR unconditionally. I believe doing that and documenting the Automake requirement is better than trying to come up with a fallback.

It's much the same for PKG_PROG_PKG_CONFIG from pkg.m4. This is only required if you want to regenerate the `configure` script. Since the `configure` script is part of the repository, there should be no need to do that unless you want to change it. And again I believe it's fair to require that pkg.m4 be installed if you want to do that.

If the `configure` script had not been part of the repository, then I would perhaps agree with your inclusion.
