### ISSUE TITLE
Cannot add libsrtp to yocto image

### ISSUE THREAD

**Issue by semofa** [cisco/libsrtp#408]
Hi,
I need to add libsrtp to my yocto image. So I added `libsrtp `to "`IMAGE_INSTALL`". But I faced the following errors:

```
Unknown package 'libsrtp'.

Collected errors:
 * opkg_solver_install: Cannot install package libsrtp.
```

**Comment by pabuhler** [comment]
@semofa , I personally have no experience with the yocto project or the process to include libraries into that project. In general packaging for various linux distributions etc has been  performed by maintainers of those distributions. If you can provide details regarding some kind of issues with libsrtp or the libsrtp build then we can try to help out but otherwise I would suggest you contact the maintainers of the yocto project.

**Comment by pabuhler** [comment]
Closing this as it not something that the libsrtp team will follow up on. If there is anything we can do to facilitate getting libsrtp in to yocto then please re open and make an explicit request.
