### ISSUE TITLE
As RTP allows sequence number to reset but SRTP does not allow - to avoid replay attacks. How they can interwork?

### ISSUE THREAD

**Issue by kapilkumar-jain** [cisco/libsrtp#424]
During Hold-resume, some of the devices change sequence number while keeping the same SSRC for the stream.
RTP allows that but SRTP doesnt. How they will interwork? does libsrtp supports this?

**Comment by pabuhler** [comment]
Hi, libsrtp has no provision for this and as you mentioned SRTP does not allow it. Best practice is to either change SSRC's or continue with the same sequence numbers. If in your application you know that it is a SSRC reuse then it is possible to remove and then re add the SSRC from the current libsrtp session.

**Comment by pabuhler** [comment]
Closing as it is not an issue in libsrtp, please reopen if you have more input.

**Comment by traud** [comment]
Any idea whose issue this is? I am asking because libSRTP is the reference implementation with API documentation.
> Best practice is to either change SSRC's or continue with the same sequence numbers.

Is that somewhere documented? If not, who would be the motivation driver to document such a Best Practice?

I tested [several](https://www.traud.de/voip) sRTP implementations with the scenario [Call Hold](https://tools.ietf.org/html/rfc5359#section-2.1). Most, near to all, use that best practice. However, some do not. Furthermore, besides Call Resume, more re-INVITE scenarios are affected, like [SIP Session Timers](https://tools.ietf.org/html/rfc4028). Although software bugs, which got reported to the manufacturers, this might be worth documentation. Don’t you think so? In that case, the first question: Where and who documents this?

One more question:
Some SIP user agents, when they hit `srtp_err_status_replay_old` aka ‘replay check failed (index too old)’, turn off sRTP Replay Protection by re-creating the whole connection to libSRTP. By that, they reset the roll-over counter (sRTP-ROC), although there is no guarantee the remote party reset that as well. I do not want to discuss the severity of that. My second and last question for today: In libSRTP, is there a clean way to disable Replay Protection after I got `srtp_err_status_replay_old`?
