### ISSUE TITLE
[question] Replay window size limit

### ISSUE THREAD

**Issue by xhaakon** [cisco/libsrtp#470]
The comment in `srtp_stream_init ()`regarding `window_size` parameter says that _Values more than 2^15 aren't meaningful due to how extended sequence numbers are calculated._

Can this limitation be explained more in detail? RTP sequence number is uint16, meaning it supports values 0 to 65535. As RFC 3711 indicates, the extended sequence count roll over happens at 2^16. So shouldn't window size meaningful limit be (2^16) - 1?

**Comment by JonathanLennox** [comment]
If you look at how the RTP extended sequence number is computed (rdbx.c in libsrtp, or Appendix A in RFC 3711), when a packet is received, a difference (mod 2^16) is computed between the sequence number of this new packet and that of the latest packet previously received.

If this difference is more than 2^15, the new packet is considered to be newer than the latest one, rather than older than it.

Thus, no packet more than 2^15 sequence numbers old will ever be interpreted as being "old" in srtp, and so it can't be referenced from the window.

**Comment by xhaakon** [comment]
Thank you, Jonathan. The explanation is clear.
