### ISSUE TITLE
meson ci builds failing for openssl on macos

### ISSUE THREAD

**Issue by pabuhler** [cisco/libsrtp#705]
see: https://github.com/cisco/libsrtp/actions/runs/8885459694

This is a meson / ci setup issue and not a libsrtp issue as far as I can tell. I can not reproduce this locally with my "older" mac.

This seamed to just start happening, not sure what has changed.

**Comment by pabuhler** [comment]
@iameli could you please take a look at this, thanks.

**Comment by pabuhler** [comment]
I have pushed a fix for now but this should be followed up so that meson ci builds can run against macos-latest again at some point.

**Comment by thewildtree** [comment]
Judging by the CI logs, the v3 issue is most likely caused by this: https://github.com/Homebrew/homebrew-core/issues/169728. Logs show that brew says `openssl@3` is already installed, so a `brew reinstall openssl@3` would likely fix the build.

As for the v1 pipeline, I think it never actually used v1 at all. Instead, it also uses `openssl@3`, as logs and the breakage together with v3 would suggest.

**Comment by pabuhler** [comment]
This is probably the case. Maybe it will be fixed soon and can move back to macos-latest . At that point should see if the v1 build actual does as expected or not.

**Comment by pabuhler** [comment]
This seams to be fixed in macos-latest now. See 0417ab9624b988987ba055688df2ca0844a11587
