### ISSUE TITLE
configure script fails when doing a static build - libraries passed in wrong place

### ISSUE THREAD

**Issue by vriera** [cisco/libsrtp#97]
When building libsrtp statically it fails at the configure phase when is testing for EVP_EncryptInit in -lcrypto:

`checking whether to leverage OpenSSL crypto... yes`
`checking for EVP_EncryptInit in -lcrypto... no`
`configure: error: in '/br/output/build/libsrtp-v1.5.0':`
`configure: error: can't find openssl >1.0.1 crypto lib`
`See 'config.log' for more details`

The real problem can be found in the config.log:

`configure:4831: checking whether to leverage OpenSSL crypto`
`configure:4840: result: yes`
`configure:4846: checking for EVP_EncryptInit in -lcrypto`
`configure:4871: /br/output/host/usr/bin/mipsel-ctng-linux-uclibc-gcc -o conftest -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -Os  -static -I/br/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include   -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -static -lssl -L/br/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr//lib -lcrypto -lz   conftest.c -lcrypto   >&5`
`/br/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr//lib/libcrypto.a(c_zlib.o): In function 'zlib_stateful_expand_block':`
`c_zlib.c:(.text+0x78): undefined reference to 'inflate'`
`/br/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr//lib/libcrypto.a(c_zlib.o): In function 'zlib_stateful_compress_block':`
`c_zlib.c:(.text+0x13c): undefined reference to 'deflate'`
[...]
`collect2: error: ld returned 1 exit status`

There is a missing `-lz` after `conftest.c`. Also, the `-lcrypto -lz` before `conftest.c` are useless. So, a command like this one would fix the problem:

`/br/output/host/usr/bin/mipsel-ctng-linux-uclibc-gcc -o conftest -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os -static -I/br/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -static -lssl -L/br/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr//lib conftest.c -lcrypto -lz`

**Comment by jfigus** [comment]
What ./configure arguments are you using to build libsrtp statically?

**Comment by vriera** [comment]
Hello jfigus,

I don't know if that rellevant. Anyway, could you please have a look to this patch? One of the Buildroot developers wrote it.

http://lists.busybox.net/pipermail/buildroot/2015-February/120140.html

It uses PKG_CHECK_MODULES instead of AC_CHECK_LIB in order to fix the problem.

Is that patch upstreamable?

**Comment by jfigus** [comment]
PKG_CHECK_MODULES is from pkg-config, not autoconf.  We could classify this issue as a feature request to include support for pkg-config. I don't see this as a bug fix.  Also, the patch doesn't ensure the appropriate revision level of OpenSSL is on the system.  It only checks for the presence of any revision of OpenSSL.  If OpenSSL 0.9.8 was on the system, then the libsrtp compiliation would fail.

**Comment by vriera** [comment]
Well, that patch was for Buildroot and our openssl version is 1.0.2.

Ok, I see your point. Then, here you have the information you requested:

./configure --target=powerpc-buildroot-linux-uclibc --host=powerpc-buildroot-linux-uclibc --build=x86_64-unknown-linux-gnu --prefix=/usr --exec-prefix=/usr --sysconfdir=/etc --localstatedir=/var --program-prefix="" --disable-dependency-tracking --enable-static --disable-shared  --with-tools=no

If you want to see the full build log, is here:

http://autobuild.buildroot.net/results/a71/a71d85a5bb9af2ee82a8e61054025bceb03dbdeb/build-end.log

**Comment by jfigus** [comment]
b5fad5f893c7f323a8f8e1c512fa48cf6cdb1c8d adds checks for libz and libdl to allow static linking of libcrypto.a.  I wasn't able to duplicate the libz issue on my system, but added this anyway since it appears your OpenSSL is likely configured different.  By the way, libsrtp doesn't recognize the --enable-static and --disable-shared options.  Your build log includes "CFLAGS=-static", which is how you're enabling the static link.

**Comment by vriera** [comment]
Hello jfigus,

I have tested your patch and I can confirm it fixes the problem. Thank you very much.

**Comment by jfigus** [comment]
Glad to help. I've used buildroot several times in the past.  It's a very useful project.  +1 for buildroot.

**Comment by RomainNaour** [comment]
Hi jfigus,

Thank you for your help.
In Buildroot, openssl is always build with zlib support, that is why we need to have -lz flag for linking with libcrypto.a.
But it's an optional dependency since zlib support can be disabled:
See Configure script in openssl:
"[no-]zlib     [don't] compile support for zlib compression"
So, it's not correct to error out when zlib is not necessary for linking with libcrypto.a.

It's the same for libdl.
See this build failure that happened after your patch has been applied in Buildroot.
http://autobuild.buildroot.net/results/a77/a770318af841610e0c10f61cf61bdae298aa59a8/build-end.log

It's not the same toolchain used in this case, this is a Blackfin toolchain which doesn't support shared libraries.

I suggest to remove AC_MSG_FAILURE if libdl or zlib is not detected.
libsrtp build fine without libdl in this specific case.

Thanks.

**Comment by jfigus** [comment]
OK, I've changed the libz and libdl checks to warnings when not found.

**Comment by Globik** [comment]
But keeps complaining that libdl not found.
